// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: user/public_user.proto

package user

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _public_user_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on LoginReq with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *LoginReq) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Username

	// no validation rules for Passwd

	return nil
}

// LoginReqValidationError is the validation error returned by
// LoginReq.Validate if the designated constraints aren't met.
type LoginReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LoginReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LoginReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LoginReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LoginReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LoginReqValidationError) ErrorName() string { return "LoginReqValidationError" }

// Error satisfies the builtin error interface
func (e LoginReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLoginReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LoginReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LoginReqValidationError{}

// Validate checks the field values on SelectRoleReq with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *SelectRoleReq) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetId() <= 0 {
		return SelectRoleReqValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
	}

	if m.GetRoleId() <= 0 {
		return SelectRoleReqValidationError{
			field:  "RoleId",
			reason: "value must be greater than 0",
		}
	}

	return nil
}

// SelectRoleReqValidationError is the validation error returned by
// SelectRoleReq.Validate if the designated constraints aren't met.
type SelectRoleReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SelectRoleReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SelectRoleReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SelectRoleReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SelectRoleReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SelectRoleReqValidationError) ErrorName() string { return "SelectRoleReqValidationError" }

// Error satisfies the builtin error interface
func (e SelectRoleReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSelectRoleReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SelectRoleReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SelectRoleReqValidationError{}

// Validate checks the field values on GetListResp with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *GetListResp) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetData() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetListRespValidationError{
					field:  fmt.Sprintf("Data[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// GetListRespValidationError is the validation error returned by
// GetListResp.Validate if the designated constraints aren't met.
type GetListRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetListRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetListRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetListRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetListRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetListRespValidationError) ErrorName() string { return "GetListRespValidationError" }

// Error satisfies the builtin error interface
func (e GetListRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetListResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetListRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetListRespValidationError{}
