// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: admin/public_admin.proto

package admin

import (
	context "context"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CreateUrlReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Passwd   string `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	Uri      string `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	SrvUri   string `protobuf:"bytes,4,opt,name=srv_uri,json=srvUri,proto3" json:"srv_uri,omitempty"`
}

func (x *CreateUrlReq) Reset() {
	*x = CreateUrlReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_public_admin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUrlReq) ProtoMessage() {}

func (x *CreateUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_public_admin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUrlReq.ProtoReflect.Descriptor instead.
func (*CreateUrlReq) Descriptor() ([]byte, []int) {
	return file_admin_public_admin_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUrlReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUrlReq) GetPasswd() string {
	if x != nil {
		return x.Passwd
	}
	return ""
}

func (x *CreateUrlReq) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *CreateUrlReq) GetSrvUri() string {
	if x != nil {
		return x.SrvUri
	}
	return ""
}

var File_admin_public_admin_proto protoreflect.FileDescriptor

var file_admin_public_admin_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x64, 0x61, 0x73, 0x68,
	0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x7f, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x64, 0x12, 0x19, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x20,
	0x0a, 0x07, 0x73, 0x72, 0x76, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x06, 0x73, 0x72, 0x76, 0x55, 0x72, 0x69,
	0x32, 0xbf, 0x01, 0x0a, 0x0b, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x12, 0x59, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x72, 0x69, 0x12, 0x1d, 0x2e,
	0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x22, 0x0a, 0x2f, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x75, 0x72, 0x69, 0x3a, 0x01, 0x2a, 0x12, 0x55, 0x0a, 0x0a, 0x47,
	0x65, 0x74, 0x55, 0x72, 0x69, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x11, 0x12, 0x0f, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x75, 0x72, 0x69, 0x2f, 0x6c, 0x69,
	0x73, 0x74, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x6f, 0x72, 0x67, 0x2f, 0x62, 0x6c, 0x75, 0x65,
	0x2d, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x3b, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_admin_public_admin_proto_rawDescOnce sync.Once
	file_admin_public_admin_proto_rawDescData = file_admin_public_admin_proto_rawDesc
)

func file_admin_public_admin_proto_rawDescGZIP() []byte {
	file_admin_public_admin_proto_rawDescOnce.Do(func() {
		file_admin_public_admin_proto_rawDescData = protoimpl.X.CompressGZIP(file_admin_public_admin_proto_rawDescData)
	})
	return file_admin_public_admin_proto_rawDescData
}

var file_admin_public_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_admin_public_admin_proto_goTypes = []interface{}{
	(*CreateUrlReq)(nil), // 0: dashboard.admin.CreateUrlReq
	(*empty.Empty)(nil),  // 1: google.protobuf.Empty
}
var file_admin_public_admin_proto_depIdxs = []int32{
	0, // 0: dashboard.admin.PublicAdmin.CreateUri:input_type -> dashboard.admin.CreateUrlReq
	1, // 1: dashboard.admin.PublicAdmin.GetUriList:input_type -> google.protobuf.Empty
	1, // 2: dashboard.admin.PublicAdmin.CreateUri:output_type -> google.protobuf.Empty
	1, // 3: dashboard.admin.PublicAdmin.GetUriList:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_admin_public_admin_proto_init() }
func file_admin_public_admin_proto_init() {
	if File_admin_public_admin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_admin_public_admin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUrlReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_admin_public_admin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_public_admin_proto_goTypes,
		DependencyIndexes: file_admin_public_admin_proto_depIdxs,
		MessageInfos:      file_admin_public_admin_proto_msgTypes,
	}.Build()
	File_admin_public_admin_proto = out.File
	file_admin_public_admin_proto_rawDesc = nil
	file_admin_public_admin_proto_goTypes = nil
	file_admin_public_admin_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PublicAdminClient is the client API for PublicAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PublicAdminClient interface {
	CreateUri(ctx context.Context, in *CreateUrlReq, opts ...grpc.CallOption) (*empty.Empty, error)
	GetUriList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
}

type publicAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewPublicAdminClient(cc grpc.ClientConnInterface) PublicAdminClient {
	return &publicAdminClient{cc}
}

func (c *publicAdminClient) CreateUri(ctx context.Context, in *CreateUrlReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/dashboard.admin.PublicAdmin/CreateUri", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicAdminClient) GetUriList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/dashboard.admin.PublicAdmin/GetUriList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicAdminServer is the server API for PublicAdmin service.
type PublicAdminServer interface {
	CreateUri(context.Context, *CreateUrlReq) (*empty.Empty, error)
	GetUriList(context.Context, *empty.Empty) (*empty.Empty, error)
}

// UnimplementedPublicAdminServer can be embedded to have forward compatible implementations.
type UnimplementedPublicAdminServer struct {
}

func (*UnimplementedPublicAdminServer) CreateUri(context.Context, *CreateUrlReq) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUri not implemented")
}
func (*UnimplementedPublicAdminServer) GetUriList(context.Context, *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUriList not implemented")
}

func RegisterPublicAdminServer(s *grpc.Server, srv PublicAdminServer) {
	s.RegisterService(&_PublicAdmin_serviceDesc, srv)
}

func _PublicAdmin_CreateUri_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUrlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicAdminServer).CreateUri(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.admin.PublicAdmin/CreateUri",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicAdminServer).CreateUri(ctx, req.(*CreateUrlReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicAdmin_GetUriList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicAdminServer).GetUriList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dashboard.admin.PublicAdmin/GetUriList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicAdminServer).GetUriList(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _PublicAdmin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dashboard.admin.PublicAdmin",
	HandlerType: (*PublicAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUri",
			Handler:    _PublicAdmin_CreateUri_Handler,
		},
		{
			MethodName: "GetUriList",
			Handler:    _PublicAdmin_GetUriList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/public_admin.proto",
}
