apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: blue-dashboard-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - "endpoints"
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: blue-dashboard-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: blue-dashboard-clusterrole
subjects:
  - kind: ServiceAccount
    name: blue-dashboard
    namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blue-dashboard
  namespace: default