apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-dashboard-deploy
  labels:
    deploy: blue-dashboard-deploy
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: blue-dashboard-pod
  template:
    metadata:
      labels:
        app: blue-dashboard-pod
    spec:
      serviceAccount: "blue-dashboard"
      containers:
        - name: dashboard
          image: "jinmz/blue-dashboard-backend:v0.0.2"
          imagePullPolicy: IfNotPresent
          args:
            - --dsn
            - "root:123@tcp(mysql-svc:3306)/dashboard?charset=utf8mb4&parseTime=True"
            - --gateway_namespace
            - "kube-system"
            - --gateway_service
            - "blue-gw-svc"
          ports:
            - name: grpc
              containerPort: 50051
              protocol: TCP
            - name: rest
              containerPort: 8081
              protocol: TCP

          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: blue-dashboard-svc
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 80
      targetPort: rest
      protocol: TCP

    - name: grpc
      port: 50051
      targetPort: grpc
      protocol: TCP

  selector:
    app: blue-dashboard-pod